// <auto-generated />
using System;
using LapTrinhMang.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LapTrinhMang.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251229133412_1")]
    partial class _1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LapTrinhMang.Models.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Phone")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("LapTrinhMang.Models.ChatMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsFromManager")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ReceiverId")
                        .HasColumnType("int");

                    b.Property<int?>("SenderId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ChatMessages");
                });

            modelBuilder.Entity("LapTrinhMang.Models.ReservationEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TableId")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TableId");

                    b.HasIndex("UserId");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("LapTrinhMang.Models.TableEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Number")
                        .IsUnique();

                    b.ToTable("Tables");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 4,
                            Number = 1,
                            Type = "Normal"
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 4,
                            Number = 2,
                            Type = "Normal"
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 4,
                            Number = 3,
                            Type = "Normal"
                        },
                        new
                        {
                            Id = 4,
                            Capacity = 4,
                            Number = 4,
                            Type = "Normal"
                        },
                        new
                        {
                            Id = 5,
                            Capacity = 4,
                            Number = 5,
                            Type = "Normal"
                        },
                        new
                        {
                            Id = 6,
                            Capacity = 4,
                            Number = 6,
                            Type = "Normal"
                        },
                        new
                        {
                            Id = 7,
                            Capacity = 4,
                            Number = 7,
                            Type = "Normal"
                        },
                        new
                        {
                            Id = 8,
                            Capacity = 4,
                            Number = 8,
                            Type = "Normal"
                        },
                        new
                        {
                            Id = 9,
                            Capacity = 4,
                            Number = 9,
                            Type = "Normal"
                        },
                        new
                        {
                            Id = 10,
                            Capacity = 4,
                            Number = 10,
                            Type = "Normal"
                        },
                        new
                        {
                            Id = 11,
                            Capacity = 6,
                            Number = 11,
                            Type = "Normal"
                        },
                        new
                        {
                            Id = 12,
                            Capacity = 6,
                            Number = 12,
                            Type = "Normal"
                        },
                        new
                        {
                            Id = 13,
                            Capacity = 6,
                            Number = 13,
                            Type = "Normal"
                        },
                        new
                        {
                            Id = 14,
                            Capacity = 6,
                            Number = 14,
                            Type = "Normal"
                        },
                        new
                        {
                            Id = 15,
                            Capacity = 6,
                            Number = 15,
                            Type = "Normal"
                        },
                        new
                        {
                            Id = 16,
                            Capacity = 6,
                            Number = 16,
                            Type = "Normal"
                        },
                        new
                        {
                            Id = 17,
                            Capacity = 6,
                            Number = 17,
                            Type = "Normal"
                        },
                        new
                        {
                            Id = 18,
                            Capacity = 6,
                            Number = 18,
                            Type = "Normal"
                        },
                        new
                        {
                            Id = 19,
                            Capacity = 6,
                            Number = 19,
                            Type = "Normal"
                        },
                        new
                        {
                            Id = 20,
                            Capacity = 6,
                            Number = 20,
                            Type = "Normal"
                        });
                });

            modelBuilder.Entity("LapTrinhMang.Models.ReservationEntity", b =>
                {
                    b.HasOne("LapTrinhMang.Models.TableEntity", "Table")
                        .WithMany()
                        .HasForeignKey("TableId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LapTrinhMang.Models.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Table");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
